# GAME : 'CartPole-v1'
GAME : 'Acrobot-v1'

BATCH_SIZE: 8
MEMORY_SIZE: 10000
MAX_TIMESTEPS: 200
MAX_EPISODES: 10000

GAMMA: 0.99
TARGET_UPDATE: 4
TAU: 0.5
LEARNING_RATE: 0.001
GAMMA_LR: 0.9
STEP_LR: 2000

# Exploration settings
EPSILON_START: 0.2
EPSILON_END: 0.05
EPSILON_DECAY: 500

DOUBLE_DQN : False
N_STEP : 1

GRAD_CLAMPING : False
