
GAME : "Acrobot-v1"
# GAME : "CartPole-v1"
# GAME : "MountainCar-v0"


MEMORY_CAPACITY : 1000000
BATCH_SIZE : 64
GAMMA : 0.99
LEARNING_RATE_CRITIC : 0.001
LEARNING_RATE_ACTOR : 0.001
TAU : 0.005

EPSILON : 0.1  # Exploration noise

MAX_EPISODES : 10000
MAX_STEPS : 10000  # Max steps per episode
